### ISSUE TITLE
Could not pass event PlayerMoveEvent to TrailGUI v4.0 org.bukkit.event.EventException

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#30]
TrailGUI dev 44.

Error spams console with the Bubbles trail activated. No trail is displayed.

```
[01:08:27] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to TrailGUI v4.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:269) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-f928e7a-e91aed8]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: There is no water at the center location
    at com.darkblade12.particleeffect.ParticleEffect.display(ParticleEffect.java:570) ~[?:?]
    at ca.jamiesinn.trailgui.trails.NormalTrail.justDisplay(NormalTrail.java:28) ~[?:?]
    at ca.jamiesinn.trailgui.trails.Trail.display(Trail.java:171) ~[?:?]
    at ca.jamiesinn.trailgui.Listeners.onPlayerMove(Listeners.java:144) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
    ... 15 more
```

Also on a side note, error is displaying version v4.0 while the plugin is version v4.2. Might want to fix that. :)

**Comment by JamieSinn** [comment]
I only update the plugin major event on major updates now
Anyway...
That looks interesting.. lemme see.

**Comment by JamieSinn** [comment]
Removing bubbles for now. 
Need to find out how to display out of water.
