### ISSUE TITLE
Error while trying to use /trail in console

### ISSUE THREAD

**Issue by hankur** [JamieSinn/TrailGUI#31]
[23:57:14 WARN]: Unexpected exception while parsing console command "trail"
org.bukkit.command.CommandException: Unhandled exception executing command 'trail' in plugin TrailGUI v4.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f928e7a-994b2aa]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-f928e7a-994b2aa]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot.jar:git-Spigot-f928e7a-994b2aa]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:628) [spigot.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:404) [spigot.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [spigot.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-f928e7a-994b2aa]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-f928e7a-994b2aa]
        at java.lang.Thread.run(Thread.java:744) [?:1.8.0]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at ca.jamiesinn.trailgui.trails.Trail.onCommand(Trail.java:359) ~[?:?]
        at ca.jamiesinn.trailgui.commands.CommandTrail.onCommand(CommandTrail.java:62) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-f928e7a-994b2aa]
        ... 8 more

**Comment by JamieSinn** [comment]
Resolved: https://github.com/JamieSinn/TrailGUI/commit/1d884e4d81adb98811d24daab609fa03e848db6d
