### ISSUE TITLE
Unexpected exception while parsing console command 

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#35]
Using TrailGUI ReloadConfigs from console.

```
[02:34:02] [Server thread/WARN]: Unexpected exception while parsing console command "TrailGUI ReloadConfigs"
org.bukkit.command.CommandException: Unhandled exception executing command 'trailgui' in plugin TrailGUI v4.2
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-PaperSpigot-ea565ef-62a2169]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-PaperSpigot-ea565ef-62a2169]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-PaperSpigot-ea565ef-62a2169]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot.jar:git-PaperSpigot-ea565ef-62a2169]
    at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416) [spigot.jar:git-PaperSpigot-ea565ef-62a2169]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [spigot.jar:git-PaperSpigot-ea565ef-62a2169]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [spigot.jar:git-PaperSpigot-ea565ef-62a2169]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [spigot.jar:git-PaperSpigot-ea565ef-62a2169]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.command.ColouredConsoleSender cannot be cast to org.bukkit.entity.Player
    at ca.jamiesinn.trailgui.commands.CommandTrailGUI.onCommand(CommandTrailGUI.java:24) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-PaperSpigot-ea565ef-62a2169]
    ... 8 more
```

**Comment by JamieSinn** [comment]
Known. Will be fixed in next release
