### ISSUE TITLE
Class 'org.bukkit.Particle' not found

### ISSUE THREAD

**Issue by mikroskeem** [JamieSinn/TrailGUI#39]
Hello! Seems TrailGUI doesn't work for me.  
I get this error:

```
java.lang.NoClassDefFoundError: org/bukkit/Particle
        at ca.jamiesinn.trailgui.trails.NormalTrail.loadType(NormalTrail.java:18) ~[?:?]
        at ca.jamiesinn.trailgui.trails.NormalTrail.<init>(NormalTrail.java:12) ~[?:?]
        at ca.jamiesinn.trailgui.TrailGUI.loadTrails(TrailGUI.java:115) ~[?:?]
        at ca.jamiesinn.trailgui.TrailGUI.load(TrailGUI.java:77) ~[?:?]
        at ca.jamiesinn.trailgui.TrailGUI.onEnable(TrailGUI.java:47) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-"5c510af"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-PaperSpigot-"5c510af"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-PaperSpigot-"5c510af"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [spigot.jar:git-PaperSpigot-"5c510af"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [spigot.jar:git-PaperSpigot-"5c510af"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [spigot.jar:git-PaperSpigot-"5c510af"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [spigot.jar:git-PaperSpigot-"5c510af"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [spigot.jar:git-PaperSpigot-"5c510af"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [spigot.jar:git-PaperSpigot-"5c510af"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [spigot.jar:git-PaperSpigot-"5c510af"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[spigot.jar:git-PaperSpigot-"5c510af"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[spigot.jar:git-PaperSpigot-"5c510af"]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
        ... 16 more
```

I'm using PaperSpigot (version: `git-PaperSpigot-"5c510af"`) and TrailGUI version `5.0-b36`

_Edit:_ Also appears with Spigot `git-Spigot-e4d4710-e1ebe5`

Is this problem caused only by TrailGUI ~~or could PaperSpigot have problems~~?

**Comment by JamieSinn** [comment]
I do not support paperspigot, and all builds above 23 are 1.9 only.

**Comment by mikroskeem** [comment]
Little correction, 23.

Build 24 is from commit 479887b and you update Bukkit API dependency there

**Comment by JamieSinn** [comment]
ah, i must have fat fingered that.
Thanks.
