### ISSUE TITLE
Could not pass event InventoryClickEvent to TrailGUI

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#40]
TrailGUI dev 36

Broke due to the potion API change in spigot here?
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/4a8818c5fd4be406c59b518b86f10f39b4e6dcdd

```
[07:38:45] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TrailGUI v5.0-b36-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.jar:git-Paper-480]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1875) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.jar:git-Paper-480]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-480]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaPotion.equalsCommon(CraftMetaPotion.java:277) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:151) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:138) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.inventory.ItemStack.isSimilar(ItemStack.java:338) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.isSimilar(CraftItemStack.java:425) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.inventory.ItemStack.equals(ItemStack.java:320) ~[patched_1.9.jar:git-Paper-480]
    at ca.jamiesinn.trailgui.trails.Trail.onInventoryClick(Trail.java:187) ~[?:?]
    at ca.jamiesinn.trailgui.Listeners.onInventoryClick(Listeners.java:56) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor384.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:42) ~[patched_1.9.jar:git-Paper-480]
    ... 16 more
[07:38:48] [Server thread/INFO]: mibby issued server command: /trails
[07:38:51] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TrailGUI v5.0-b36-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.jar:git-Paper-480]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1875) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.jar:git-Paper-480]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-480]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaPotion.equalsCommon(CraftMetaPotion.java:277) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:151) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:138) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.inventory.ItemStack.isSimilar(ItemStack.java:338) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.isSimilar(CraftItemStack.java:425) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.inventory.ItemStack.equals(ItemStack.java:320) ~[patched_1.9.jar:git-Paper-480]
    at ca.jamiesinn.trailgui.trails.Trail.onInventoryClick(Trail.java:187) ~[?:?]
    at ca.jamiesinn.trailgui.Listeners.onInventoryClick(Listeners.java:56) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor384.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:42) ~[patched_1.9.jar:git-Paper-480]
    ... 16 more
[07:38:51] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TrailGUI v5.0-b36-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.jar:git-Paper-480]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1875) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.jar:git-Paper-480]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-480]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaPotion.equalsCommon(CraftMetaPotion.java:277) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:151) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:138) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.inventory.ItemStack.isSimilar(ItemStack.java:338) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.isSimilar(CraftItemStack.java:425) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.inventory.ItemStack.equals(ItemStack.java:320) ~[patched_1.9.jar:git-Paper-480]
    at ca.jamiesinn.trailgui.trails.Trail.onInventoryClick(Trail.java:187) ~[?:?]
    at ca.jamiesinn.trailgui.Listeners.onInventoryClick(Listeners.java:56) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor384.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:42) ~[patched_1.9.jar:git-Paper-480]
    ... 16 more
[07:38:51] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TrailGUI v5.0-b36-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.jar:git-Paper-480]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1875) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.jar:git-Paper-480]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-480]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaPotion.equalsCommon(CraftMetaPotion.java:277) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:151) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:138) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.inventory.ItemStack.isSimilar(ItemStack.java:338) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.isSimilar(CraftItemStack.java:425) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.inventory.ItemStack.equals(ItemStack.java:320) ~[patched_1.9.jar:git-Paper-480]
    at ca.jamiesinn.trailgui.trails.Trail.onInventoryClick(Trail.java:187) ~[?:?]
    at ca.jamiesinn.trailgui.Listeners.onInventoryClick(Listeners.java:56) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor384.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:42) ~[patched_1.9.jar:git-Paper-480]
    ... 16 more
[07:38:52] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TrailGUI v5.0-b36-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.jar:git-Paper-480]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.jar:git-Paper-480]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1875) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.jar:git-Paper-480]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-480]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-480]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaPotion.equalsCommon(CraftMetaPotion.java:277) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:151) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:138) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.inventory.ItemStack.isSimilar(ItemStack.java:338) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.isSimilar(CraftItemStack.java:425) ~[patched_1.9.jar:git-Paper-480]
    at org.bukkit.inventory.ItemStack.equals(ItemStack.java:320) ~[patched_1.9.jar:git-Paper-480]
    at ca.jamiesinn.trailgui.trails.Trail.onInventoryClick(Trail.java:187) ~[?:?]
    at ca.jamiesinn.trailgui.Listeners.onInventoryClick(Listeners.java:56) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor384.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:42) ~[patched_1.9.jar:git-Paper-480]
    ... 16 more
```

**Comment by JamieSinn** [comment]
Yes, this is because of the potion update.
I'll look into it.

**Comment by JamieSinn** [comment]
You are using paperspigot, I do not support it. Please re-create this bug using regular spigot.

**Comment by mibby** [comment]
@JamieSinn Not sure why you wouldn't, as PaperSpigot is nearly identical to normal Spigot with just some additional performance patches from many guys who contributed to Spigot back in the day, such as Aikar who created the Spigot v1 timings, Paper has v2+.

Anyhow, this issue is still present with Spigot git-Spigot-104c8c8-00d3334.
TrailGUI dev 36.

Error occurs when clicking on the MagicCrit and BlackPotion trails in the GUI.

```
[20:03:15] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TrailGUI v5.0-b36-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1852) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_74]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_74]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaPotion.equalsCommon(CraftMetaPotion.java:277) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:151) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:138) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.inventory.ItemStack.isSimilar(ItemStack.java:338) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.isSimilar(CraftItemStack.java:425) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.inventory.ItemStack.equals(ItemStack.java:320) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at ca.jamiesinn.trailgui.trails.Trail.onInventoryClick(Trail.java:187) ~[?:?]
    at ca.jamiesinn.trailgui.Listeners.onInventoryClick(Listeners.java:56) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_74]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    ... 15 more
```

```
[20:03:20] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TrailGUI v5.0-b36-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1852) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_74]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_74]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-104c8c8-00d3334]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaPotion.equalsCommon(CraftMetaPotion.java:277) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:151) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:138) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.inventory.ItemStack.isSimilar(ItemStack.java:338) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.isSimilar(CraftItemStack.java:425) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.inventory.ItemStack.equals(ItemStack.java:320) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    at ca.jamiesinn.trailgui.trails.Trail.onInventoryClick(Trail.java:187) ~[?:?]
    at ca.jamiesinn.trailgui.Listeners.onInventoryClick(Listeners.java:56) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_74]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-104c8c8-00d3334]
    ... 15 more
```

**Comment by JamieSinn** [comment]
It's because of just that. _nearly_ isn't identical.
