### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by andrewkm** [JamieSinn/TrailGUI#42]
http://pastie.org/private/kdobpws5dv6to4ohy8ln2a

**Comment by JamieSinn** [comment]
Don't use the latest Dev just yet, I'm working on making it backwards compatible with 1.8, use the release on Spigot

**Comment by mibby** [comment]
Ah, was just about to report this problem as well. On dev build 41.

```
[16:28:14] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to TrailGUI v5.0-b41-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.4.jar:git-Paper-748]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.4.jar:git-Paper-748]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.4.jar:git-Paper-748]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.4.jar:git-Paper-748]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.4.jar:git-Paper-748]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:608) [patched_1.9.4.jar:git-Paper-748]
    at net.minecraft.server.v1_9_R2.PacketPlayInFlying.a(SourceFile:126) [patched_1.9.4.jar:git-Paper-748]
    at net.minecraft.server.v1_9_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [patched_1.9.4.jar:git-Paper-748]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-748]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-748]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-748]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-748]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-748]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-748]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
    at ca.jamiesinn.trailgui.ParticleManager.spawnParticle(ParticleManager.java:28) ~[?:?]
    at ca.jamiesinn.trailgui.trails.NormalTrail.justDisplay(NormalTrail.java:28) ~[?:?]
    at ca.jamiesinn.trailgui.trails.Trail.display(Trail.java:165) ~[?:?]
    at ca.jamiesinn.trailgui.Listeners.onPlayerMove(Listeners.java:145) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor412.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.4.jar:git-Paper-748]
    ... 16 more
```
