### ISSUE TITLE
NullPointerException on shutdown

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#46]
TrailGUI dev 59

```
[21:17:35 INFO]: [TrailGUI] Disabling TrailGUI v5.0.1-b59-SNAPSHOT
[21:17:35 ERROR]: Error occurred while disabling TrailGUI v5.0.1-b59-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
        at ca.jamiesinn.trailgui.TrailGUI.onDisable(TrailGUI.java:181) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[patched_1.10.2.jar:git-Paper-828]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:347) [patched_1.10.2.jar:git-Paper-828]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [patched_1.10.2.jar:git-Paper-828]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420) [patched_1.10.2.jar:git-Paper-828]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.disablePlugins(CraftServer.java:337) [patched_1.10.2.jar:git-Paper-828]
        at net.minecraft.server.v1_10_R1.MinecraftServer.stop(MinecraftServer.java:453) [patched_1.10.2.jar:git-Paper-828]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:660) [patched_1.10.2.jar:git-Paper-828]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
```

**Comment by andrewkm** [comment]
Same issue here. Please revert build for now.

**Comment by JamieSinn** [comment]
This is fixed in latest ci build. Will be posted to spigot when I'm home
