### ISSUE TITLE
EventException - PlayerQuitEvent on logout.

### ISSUE THREAD

**Issue by mibby** [JamieSinn/TrailGUI#51]
TrailGUI v5.15-b68

Problem commit.
https://github.com/JamieSinn/TrailGUI/commit/16d155e5f863a4fbdef951db11c74e392d26ba2a

TrailGUI v5.2 snapshot (jenkins dev 67) is perfectly fine.
https://ci.md-5.net/job/TrailGUI/67/

```
[09:53:58] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to TrailGUI v5.15-b68-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1062]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.11.2.jar:git-Paper-1062]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1062]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1062]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.PlayerList.disconnect(PlayerList.java:404) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1064) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.NetworkManager.handleDisconnection(NetworkManager.java:324) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:184) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:925) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1062]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1062]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at ca.jamiesinn.trailgui.Util.saveTrails(Util.java:66) ~[?:?]
	at ca.jamiesinn.trailgui.Listeners.onLogout(Listeners.java:162) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor533.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1062]
	... 13 more
```

**Comment by JamieSinn** [comment]
The config has been updated, please see the new config. After that, please try again.

**Comment by JamieSinn** [comment]
Try with latest commit. Will be pushing to spigot later
