### ISSUE TITLE
MySQL CommunicationsException

### ISSUE THREAD

**Issue by hankur** [JamieSinn/TrailGUI#53]
TrailGUI version 5.15-b70-SNAPSHOT throws a CommunicationsException every time someone logs out:
```
[15:10:54 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 37,339,536 milliseconds ago.  The last packet sent successfully to the server was 37,339,537 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[15:10:54 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:10:54 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:10:54 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:10:54 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[15:10:54 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[15:10:54 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
[15:10:54 WARN]:        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3746)
[15:10:54 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2509)
[15:10:54 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[15:10:54 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490)
[15:10:54 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[15:10:54 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[15:10:54 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
[15:10:54 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
[15:10:54 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
[15:10:54 WARN]:        at ca.jamiesinn.trailgui.sql.SQLManager.insertUser(SQLManager.java:88)
[15:10:54 WARN]:        at ca.jamiesinn.trailgui.Util.saveTrails(Util.java:51)
[15:10:54 WARN]:        at ca.jamiesinn.trailgui.Listeners.onLogout(Listeners.java:162)
[15:10:54 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:10:54 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:10:54 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:10:54 WARN]:        at java.lang.reflect.Method.invoke(Method.java:483)
[15:10:54 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[15:10:54 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:10:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[15:10:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[15:10:54 WARN]:        at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:399)
[15:10:54 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1095)
[15:10:54 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:321)
[15:10:54 WARN]:        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:174)
[15:10:54 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842)
[15:10:54 WARN]:        ... 4 more
[15:10:54 WARN]: Caused by: java.net.SocketException: Broken pipe
[15:10:54 WARN]:        at java.net.SocketOutputStream.socketWrite0(Native Method)
[15:10:54 WARN]:        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
[15:10:54 WARN]:        at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
[15:10:54 WARN]:        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
[15:10:54 WARN]:        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
[15:10:54 WARN]:        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3728)
[15:10:54 WARN]:        ... 28 more
```
"autoReconnect=true" isn't really reliable, why don't you use Connection#isValid(), for example, before using Connection instance?

**Comment by JamieSinn** [comment]
When I designed the MySQL addon, I expected it to make a single connection once started, and use that throughout. This was mostly due to the lag that creating/running/closing connections causes when done on a massive server scale (500+ logging in at once will crash a server due to the 500 connections).

I'll re-connect if the connection is lost, hopefully that won't cause too much damage.
